/**
 * email-inbound — Resend inbound email webhook handler.
 *
 * Route: POST /functions/v1/email-inbound  (no auth required — public webhook)
 *
 * When an email arrives at bugs@icareeros.com, Resend POSTs a JSON payload here.
 * This function:
 *   1. Validates the webhook secret (RESEND_WEBHOOK_SECRET env var)
 *   2. Parses sender, subject, and body
 *   3. Looks up the sender in auth.users (to link to existing account if any)
 *   4. Creates a support_ticket (source='email')
 *   5. Creates the first ticket_message with the email body
 *   6. Sends a confirmation email via support-notify
 *
 * DNS setup required (one-time, done in Resend dashboard):
 *   Add MX record: bugs.icareeros.com → inbound.resend.com (priority 10)
 *   OR configure Resend domain catch-all inbound routing for icareeros.com.
 *   Set RESEND_WEBHOOK_SECRET in Supabase secrets to match the Resend signing secret.
 */

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { log } from "../_shared/logger.ts";

/** Strip HTML tags for plain-text body extraction */
function stripHtml(html: string): string {
  return html.replace(/<[^>]+>/g, " ").replace(/\s{2,}/g, " ").trim();
}

/** Extract a clean body — prefer plain text, fall back to stripped HTML */
function extractBody(text?: string, html?: string): string {
  if (text?.trim()) return text.trim().slice(0, 8000);
  if (html?.trim()) return stripHtml(html).slice(0, 8000);
  return "(no body)";
}

/** Map email subject keywords to category */
function subjectToCategory(subject: string): string {
  const s = subject.toLowerCase();
  if (s.includes("bug") || s.includes("error") || s.includes("broken")) return "bug";
  if (s.includes("feature") || s.includes("request")) return "feature_request";
  if (s.includes("account") || s.includes("login") || s.includes("password")) return "account";
  if (s.includes("billing") || s.includes("payment") || s.includes("invoice")) return "billing";
  return "general";
}

Deno.serve(async (req) => {
  // Only accept POST
  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  // ── Webhook secret validation ─────────────────────────────────────────────
  const webhookSecret = Deno.env.get("RESEND_WEBHOOK_SECRET");
  if (webhookSecret) {
    const signature = req.headers.get("svix-signature") ?? req.headers.get("x-resend-signature");
    if (!signature || !signature.includes(webhookSecret)) {
      log("warn", "email-inbound: invalid webhook signature");
      return new Response("Unauthorized", { status: 401 });
    }
  }

  // ── Parse payload ─────────────────────────────────────────────────────────
  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return new Response("Invalid JSON", { status: 400 });
  }

  // Resend inbound payload shape
  const from: string = (body.from as string) ?? "";
  const subject: string = (body.subject as string) ?? "(no subject)";
  const text: string | undefined = body.text as string | undefined;
  const html: string | undefined = body.html as string | undefined;

  if (!from) {
    log("warn", "email-inbound: missing from address");
    return new Response("Bad request", { status: 400 });
  }

  // Extract plain email address from "Name <email>" format
  const fromEmailMatch = from.match(/<([^>]+)>/) ?? from.match(/^([^\s]+)/);
  const fromEmail = fromEmailMatch ? fromEmailMatch[1].toLowerCase() : from.toLowerCase();

  const emailBody = extractBody(text, html);
  const title = subject.slice(0, 100) || "(no subject)";
  const category = subjectToCategory(subject);

  log("info", "email-inbound: processing", { from: fromEmail, subject: title });

  // ── Supabase service client (bypasses RLS for ticket creation) ────────────
  const supabase = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
  );

  // Look up existing user by email
  const { data: userList } = await supabase.auth.admin.listUsers();
  const matchedUser = userList?.users?.find(
    (u) => u.email?.toLowerCase() === fromEmail,
  );
  const userId: string | null = matchedUser?.id ?? null;

  // ── Create ticket ─────────────────────────────────────────────────────────
  const { data: ticket, error: ticketErr } = await supabase
    .from("support_tickets")
    .insert({
      user_id: userId,
      guest_email: userId ? null : fromEmail,
      title,
      category,
      request_type: "general_feedback",
      priority: "normal",
      status: "open",
      source: "email",
      // ticket_number generated by DB trigger
      ticket_number: "",
    })
    .select("id, ticket_number")
    .single();

  if (ticketErr || !ticket) {
    log("error", "email-inbound: failed to create ticket", { error: ticketErr?.message });
    return new Response("Failed to create ticket", { status: 500 });
  }

  // ── Create first message ──────────────────────────────────────────────────
  const { error: msgErr } = await supabase.from("ticket_messages").insert({
    ticket_id: ticket.id,
    user_id: userId,
    body: emailBody,
    is_internal_note: false,
    is_staff_reply: false,
  });

  if (msgErr) {
    log("error", "email-inbound: failed to create message", { error: msgErr.message });
    // Don't fail the whole request — ticket exists, message can be added manually
  }

  log("info", "email-inbound: ticket created", {
    ticketNumber: ticket.ticket_number,
    from: fromEmail,
    userId,
  });

  // ── Send confirmation email ───────────────────────────────────────────────
  const notifyUrl = `${Deno.env.get("SUPABASE_URL")}/functions/v1/support-notify`;
  fetch(notifyUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")}`,
    },
    body: JSON.stringify({
      event: "ticket_created",
      to: fromEmail,
      ticketNumber: ticket.ticket_number,
      ticketTitle: title,
    }),
  }).catch(() => { /* fire-and-forget */ });

  return new Response(
    JSON.stringify({ ok: true, ticketNumber: ticket.ticket_number }),
    { headers: { "Content-Type": "application/json" } },
  );
});
