import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2 } from "lucide-react";
import jsPDF from "jspdf";
import { toast } from "sonner";

interface Props {
  profile: {
    full_name?: string;
    email?: string;
    phone?: string;
    location?: string;
    summary?: string;
    skills?: string[];
    work_experience?: { title: string; company: string; startDate: string; endDate: string; description: string }[];
    education?: { degree: string; institution: string; year: string }[];
    certifications?: string[];
    career_level?: string;
  };
  portfolio?: { title: string; item_type: string; description?: string; url?: string; tags?: string[] }[];
}

export default function ProfilePdfExport({ profile, portfolio }: Props) {
  const [generating, setGenerating] = useState(false);

  const generate = () => {
    setGenerating(true);
    try {
      const doc = new jsPDF();
      const margin = 15;
      let y = margin;
      const lineH = 6;
      const pageW = 180;

      const addLine = (text: string, bold = false, size = 10) => {
        if (y > 270) { doc.addPage(); y = margin; }
        doc.setFontSize(size);
        doc.setFont("helvetica", bold ? "bold" : "normal");
        const lines = doc.splitTextToSize(text, pageW);
        lines.forEach((line: string) => {
          if (y > 270) { doc.addPage(); y = margin; }
          doc.text(line, margin, y);
          y += lineH;
        });
      };

      const addSection = (title: string) => {
        y += 4;
        addLine(title, true, 13);
        y += 2;
      };

      // Header
      addLine(profile.full_name || "Professional Profile", true, 20);
      y += 2;
      if (profile.career_level) addLine(profile.career_level, false, 11);
      const contact = [profile.email, profile.phone, profile.location].filter(Boolean).join(" • ");
      if (contact) addLine(contact, false, 9);
      y += 4;

      // Summary
      if (profile.summary) {
        addSection("Summary");
        addLine(profile.summary);
      }

      // Skills
      if (profile.skills?.length) {
        addSection("Skills");
        addLine(profile.skills.join(", "));
      }

      // Experience
      if (profile.work_experience?.length) {
        addSection("Experience");
        profile.work_experience.forEach(exp => {
          addLine(`${exp.title} — ${exp.company}`, true, 11);
          addLine(`${exp.startDate} – ${exp.endDate || "Present"}`, false, 9);
          if (exp.description) addLine(exp.description);
          y += 2;
        });
      }

      // Education
      if (profile.education?.length) {
        addSection("Education");
        profile.education.forEach(edu => {
          addLine(`${edu.degree} — ${edu.institution}${edu.year ? ` (${edu.year})` : ""}`, false, 11);
        });
      }

      // Certifications
      if (profile.certifications?.length) {
        addSection("Certifications");
        addLine(profile.certifications.join(", "));
      }

      // Portfolio
      if (portfolio?.length) {
        addSection("Portfolio");
        portfolio.forEach(item => {
          addLine(`[${item.item_type}] ${item.title}`, true, 11);
          if (item.description) addLine(item.description);
          if (item.url) addLine(item.url, false, 9);
          y += 2;
        });
      }

      // Footer
      y += 6;
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("Generated by iCareerOS", margin, 285);

      doc.save(`${(profile.full_name || "profile").replace(/\s+/g, "_")}_profile.pdf`);
      toast.success("PDF downloaded!");
    } catch {
      toast.error("Failed to generate PDF");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Button variant="outline" size="sm" onClick={generate} disabled={generating}>
      {generating ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : <Download className="w-4 h-4 mr-1" />}
      Download PDF
    </Button>
  );
}
